[package]
name = "synked-service"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
serde = "1.0.228"
serde_json = "1.0.149"
synked-service-data = { path = "../synked-service-data" }
uuid = "1.19.0"
