[package]
name = "synked-service-data"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.43", features = ["serde"]}
serde = { version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
uuid = { version = "1.19.0", features = ["v4", "serde"]}
